# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71bb4cf6f603a0e0f2da7e1f8b5f41fd3419f87d4e9f31b2649ea66ae02919e4325c8bbd7358f61e8b50231671b570396686cc8217771267e3bff6bede0fe8f6

test:
  secret_key_base: 4782c34c770189503bd1866896f1f781ad06aafe633d6ee388d982a528e22d82cf09c807d588de79be7bd4630546cad937f1e4ddabfecdc46779b549094a3a97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
